# .github/workflows/core.yml
name: notarizador-web-build
on:
  pull_request:
    branches: [ dev, master, uat ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install NPM dependencies
        run: npm i
      - name: Build Project
        run: npm run build
